# Generated by Django 3.2.12 on 2022-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Arts-culture', 'Arts-culture'), ('Technology', 'Technology'), ('Movies-music', 'Movies-music'), ('Travel', 'Travel')], max_length=250),
        ),
    ]
